application: tuiter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: handlers.main.app
  login: required

- url: /tuits/new
  script: handlers.tuits.new.app
  login: required

- url: /tuits/list
  script: handlers.tuits.list.app
  login: required

- url: /tuits/created
  script: handlers.tuits.created.app
  login: required

- url: /likes/new
  script: handlers.likes.new.app
  login: required

- url: /likes/list
  script: handlers.likes.list.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"

